version: "3.3"
services:
  sonar:
    image: ghcr.io/obeone/sonarqube-ecocode:9.3-community
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    depends_on:
      - db
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    volumes:
      - "extensions:/opt/sonarqube/extensions"
      - "logs:/opt/sonarqube/logs"
      - "data:/opt/sonarqube/data"

  db:
    image: postgres:12
    container_name: postgresql
    networks:
      - sonarnet
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
      PGDATA: pg_data:/var/lib/postgresql/data/pgdata

networks:
  sonarnet:
    driver: bridge

volumes:
  data:
  logs:
  extensions:
  pg_data:
